### ISSUE TITLE
Não consigo colocar para funcionar

### ISSUE THREAD

**Issue by samukets** [highlandr/service.subtitles.pipocas#3]
Olá amigos, sempre que tento rodar o addon, mesmo configurado com meu login e senha, o mesmo me informa que legendas somente em português brazil, inglês, português e não me retorna nada além dessa mensagem. Uso o Kodi na linguagem English mas as configurações de legendas estão para baixar em português Brasil, o que pode ser?

**Comment by highlandr** [comment]
Hmmm. Vou testar. Estava a funcionar.

**Comment by highlandr** [comment]
Testei e funciona.
Lembro que nos settings do Kodi (não estou a falar dos settings do plugin) tens que escolher as linguas que queres. Por defeito só tem o Inglês o que causa não aparecer nada. Eu também uso o Kodi em inglês e tive que ir escolher.
